- README.md
- examples/dynamodb/main.tf
- examples/iam/main.tf
- examples/rds/main.tf
- examples/redis/main.tf
- variables.tf
This PR changes the `tags` variable from optional (defaulted to `{}`) to mandatory without a default. This way we can ensure everybody needs at least think about the tags to add and cannot accidentally forget it.
Upcoming git tag: `v0.1.1`
> Ensure tags is a required variable instead of optional

- Makefile
This PR ensures that Docker images are up-to-date with what is available upstream (preventing you from running an outdated version locally) and also fixes an issue with wrong variable usage for the Docker image tag (previously: `${var}` now: `$(var)`)
> Makefile fixes (ci-only)

- Makefile
- rds.tf
Currently the specified tags are not passed on to the security group module. This PR fixes that.
Upcoming git tag will be: `v2.0.1`
> OPS-0 Add missing tags to security group

- README.md
- examples/dynamodb/README.md
- examples/iam/README.md
- examples/rds/README.md
- examples/redis/README.md
- rds.tf
- variables.tf
Adding an override variable for the db name.
In some cases it can be wishful that the identifier should not be taken for the db name.
> rds_dbname_override

- rds.tf
Disabling `performance_insights_retention_period` by nulling it.
Underlying module + AWS Provider is not handling performance_insights_retention_period correctly.
> disabling performance_insights_retention_period

- iam.tf
Give user permissions as well, next to Role, this allows the service to access services directly, in the same way as they would when they have a role pegged.
Simplifies life for DevOps and Developers :-)
> Adding user-specific permissions next to role-permissions

- s3.tf
Every lifecycle-rule has an enabled flag we currently have to pass as parameter, this feels redundant. This change sets the enabled flag to true by default
> set lifecycle_rule 'enabled' to true by default, no need to pass it as parameter

- rds.tf
Not really a "microservice" anymore when you consider OracleSQL, but here goes...
To be used here: https://github.com/Flaconi/ops-infra-maze/pull/292
> OPS-0 Adds support for OracleSQL RDS instances

- vpc_and_subnets.tf
W/o this fix, all the SGs in that particular VPC would be attached to the RDS instance, if the list would be kept empty.
> Fixes conditional for attaching additional SGs to the RDS

- README.md
- dynamodb.tf
- dynamodb_2.tf
- dynamodb_3.tf
- rds.tf
- variables.tf
The following 
- dynamodb_enabled
-dynamodb_enable_autoscaler
Are already boolean variables, it doesn't need the conditional expression, this variables are initialised as false by default.
There is a [commit](https://github.com/terraform-aws-modules/terraform-aws-rds/commit/bdc2de20ced43490d02f61be4c704eae282785fb) in the module for rds that has not been yet merged into master this will avoid the problem of the creation by default of the option groups and parameter groups.
To avoid this the variables:
- rds_option_group_name
- rds_parameter_group_name
Were set to the value `default` instead of an empty string
> OPS-0 Changes for dynamodb conditionals and rds option/parameter groups

- README.md
- redis.tf
- variables.tf
`apply_immediately is set to false as default` (see here: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group#apply_immediately)
Next tag will be `v2.9.0`
> Redis: apply_immediately is set to false as default

- README.md
- rds.tf
- variables.tf
This partially reverts this commit: https://github.com/Flaconi/terraform-aws-microservice/pull/41/commits/22d3cd70a5b0e450538a4fa56e9c4055b0a832d8
Without this, we can't set options for the RDS option groups.
Upcoming release tag: `v2.10.0`
> Allows setting RDS options

- rds.tf
This is needed, so that the RDS instance can store its dump files but can also read them back, while the S3 objects are encrypted with KMS.
Upcoming release tag: `v2.10.1`
> Allows handling the encrypted database dump files

- rds.tf
RDS doesn't send, for example, PUT requests with the encryption related header.
We're locking down the access to the bucket by using the RDS IAM role.
Upcoming release tag: `v2.10.2`
> Fix rds s3 access policy

- README.md
- route53.tf
- variables.tf
Adds support for SQLServer engines for Route53 endpoints and allows to use custom subdomains.
> Adds support for custom SQLServer DNS Records

- rds.tf
Passes missing ARN of the IAM role created for enhanced monitoring and gracefully ignores wrong performance monitoring intervals.
> Adds enhanced monitoring role ARN to RDS instance

- route53.tf
Adds oracle engine to supported RDS DNS subdomains.
> Adds support for Oracle RDS

- README.md
- rds.tf
- variables.tf
Allows the user to specify IOPS settings of an RDS instance. If it is set, the storage type will be set to `io1` automatically.
> Allows RDS IOPS configuration

- README.md
- rds.tf
- variables.tf
For handling long-running operations.
Upcoming release: `v3.0.4`
> Allows users to specify RDS operations timeouts

- README.md
- redis.tf
- variables.tf
In order to unblock `terragrunt/envs/aws/prod/eu-central-1/microservices/ui-shop-gateway` on 
https://github.com/Flaconi/ops-infra-maze/pull/716#issuecomment-912364306
So I have to add a variable to enable multi-az in elasticache resource
---
Default value is false in dev and testing env. 
Ture in prod env
> OPS-0 Add variable to enable multi-az for elasticache replication group

- README.md
- iam.tf
- kms.tf
- rds.tf
- variables.tf
Self-explanatory.
Upcoming release: `v3.1.0`
> Allows RDS DB dumps stored in S3 buckets to be accessible cross-account

- .gitignore
- rds-s3-dumps.tf
Fix the following error when `terraform plan` in `examples/dynamodb/`
Coming release is v3.3.1
```
│ Error: Invalid index
│ 
│   on ../../rds-s3-dumps.tf line 7, in locals:
│    7:       [aws_iam_role.rds_dumps[0].arn],
│     ├────────────────
│     │ aws_iam_role.rds_dumps is empty tuple
│ 
│ The given key does not identify an element in this collection value: the collection has no elements.
```
> OPS-0 Fix aws_iam_role.rds_dump is empty list

- README.md
- examples/rds/main.tf
- rds-s3-dumps.tf
- variables.tf
> Allows S3 Lifecycle for RDS Dump Bucket

- README.md
- rds-s3-dumps.tf
- s3.tf
- variables.tf
> Allow lifecycle rules for noncurrent objects

- README.md
- rds.tf
- variables.tf
Since AWS RDS supports new storage types, namely io2 and gp3 that both support provisioned IOPS, it makes sense to remove the opinionated approach once taken and to allow free choice of storage type instead of forcing to io1. Also, changing default to gp3 to use the latest and greatest general purpose storage type by default.
> Allow-Multiple-Storage-Types-With-Provisioned-IOPS
